// This is a sample SwiftUI App entry point generated by your AI agent.
// All Swift/ObjC code in this folder is managed by the AI and can be edited in VS Code or Xcode.
// The AI will always consult Copilot for best practices, debugging, and Apple platform guidelines before making changes.

import SwiftUI

@main
struct AIApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
