// This is a sample SwiftUI view generated by your AI agent.
// The AI will always consult Copilot for best practices and UI/UX guidelines before making changes.

import SwiftUI

struct ContentView: View {
    var body: some View {
        VStack {
            Text("Hello from your AI-powered Xcode app!")
                .font(.title)
                .padding()
            Text("All code here is managed by your AI agent.")
                .font(.subheadline)
                .foregroundColor(.gray)
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
