// Simple, functional SwiftUI GUI generated by your AI agent.
// Follows Apple best practices and your project's workflow rules.
// All code is placed in xcode-project/ to avoid conflicts with VS Code scripts and backend.

import SwiftUI

struct SimpleGUI: View {
    @State private var username: String = ""
    @State private var isLoggedIn: Bool = false

    var body: some View {
        VStack(spacing: 24) {
            Text("Welcome to the AI-Powered App!")
                .font(.largeTitle)
                .padding(.top, 40)
            if !isLoggedIn {
                TextField("Enter your username", text: $username)
                    .textFieldStyle(RoundedBorderTextFieldStyle())
                    .padding(.horizontal, 40)
                Button("Login") {
                    if !username.isEmpty {
                        isLoggedIn = true
                    }
                }
                .buttonStyle(.borderedProminent)
            } else {
                Text("Hello, \(username)!")
                    .font(.title2)
                Button("Logout") {
                    isLoggedIn = false
                    username = ""
                }
                .buttonStyle(.bordered)
            }
            Spacer()
        }
        .padding()
        .accessibilityElement(children: .contain)
    }
}

struct SimpleGUI_Previews: PreviewProvider {
    static var previews: some View {
        SimpleGUI()
    }
}
